"""add: digest

Revision ID: e7f943bcd257
Revises: 0f4abeddbb0a
Create Date: 2024-12-25 08:18:51.411220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7f943bcd257'
down_revision: Union[str, None] = '0f4abeddbb0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('s3_url', sa.String(), nullable=False),
    sa.Column('article_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digests_end_datetime'), 'digests', ['end_datetime'], unique=False)
    op.create_index(op.f('ix_digests_start_datetime'), 'digests', ['start_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_digests_start_datetime'), table_name='digests')
    op.drop_index(op.f('ix_digests_end_datetime'), table_name='digests')
    op.drop_table('digests')
    # ### end Alembic commands ###
